### ISSUE TITLE
conflict with Light/Sound Mask

### ISSUE THREAD

**Issue by pumpkin1972** [Aedif/token-sounds#3]
When running this module with Light/Sound Mask module, when right clicking on a token and selecting add new sound, the pop up does not occur. No other modules other than required ones are running - Token-sounds works as expected if light/sound mask module is disabled
Happy to raise this with the author of Light/Sound Mask if needed

Thanks
This error is in the foundry logs -

foundry.js:753 TypeError: An error occurred while rendering AmbientSoundCustomConfig 50. Cannot read properties of null (reading 'clone')
[Detected 3 packages: lightmask, lib-wrapper, aedifs-token-sounds]
    at AmbientSoundCustomConfig._render (AmbientSoundConfig.js:56:42)
    at 🎁AmbientSoundConfig.prototype._render#0 (libWrapper-wrapper.js:187:52)
    at AmbientSoundCustomConfig.render (foundry.js:5769:10)
    at AmbientSoundCustomConfig.render (foundry.js:7111:18)
    at _onAddSoundClick (tokenHooks.js:201:54)
    at HTMLDivElement.<anonymous> (tokenHooks.js:147:29)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by Aedif** [comment]
That's probably something for Ligt/Sound Mask to fix. I think that module is assuming that the opened configuration form has an associated AmbientSound placeable on the canvas. Which in the case of 'Sound of Token' it doesn't.

The normal Foundry form does not make those assumptions so it would be more appropriate for that module not to do that either.

This actually also causes a clash with Mass Edit, which also opens Ambient Sound configuration forms without the sound being on the canvas.

**Comment by pumpkin1972** [comment]
thanks. I'll raise with the other developer
